# Generated by Django 5.1.4 on 2025-01-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20250104_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoactividad',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada'), ('En Progreso', 'En Progreso')], default='Pendiente', max_length=50),
        ),
    ]
