# Generated by Django 5.1.4 on 2025-01-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_estadoactividad_estado'),
    ]

    operations = [
    ]
